language: php
sudo: false
php:
    - 7.1
    - 7.0
    - 5.6

install:
    - composer install --no-dev

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
